name: ci

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.12-beta
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib example
